apiVersion: v1
kind: Service
metadata:
  name: {{ include "soba.fullname" . }}-be
  labels:
    {{- include "soba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.be_service.type }}
  ports:
    - port: {{ .Values.be_service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "soba.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "soba.fullname" . }}-fe
  labels:
    {{- include "soba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fe_service.type }}
  ports:
    - port: {{ .Values.fe_service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "soba.selectorLabels" . | nindent 4 }}